### ISSUE TITLE
pdf version

### ISSUE THREAD

**Issue by emil-lab** [tjmonsi/chi2016-program#4]
Hi,
There is a pdf version of schedule?
Thanks

**Comment by tjmonsi** [comment]
Yes :) You can download them at https://chi2016.acm.org/wp/wp-content/uploads/2016/05/chi2016-program-final-for-web-2.pdf

**Comment by emil-lab** [comment]
Thanks a lot!!!

[ENG Emiliano Labrador Ruiz de la Hermosa]
[cid:image002.gif@01CB49FA.E8BA3480]<http://blogs.salleurl.edu/>

[cid:image003.jpg@01CB49FA.E8BA3480]<http://www.facebook.com/LaSalleBCN>

[cid:image004.jpg@01CB49FA.E8BA3480]<http://twitter.com/LaSalleBCN>

[cid:image005.jpg@01CB49FA.E8BA3480]<http://es.linkedin.com/in/beslasalle>

[cid:image006.jpg@01CB49FA.E8BA3480]<www.youtube.com/LaSalleBCN>

[cid:image007.jpg@01CB49FA.E8BA3480]<http://www.flickr.com/photos/beslasalle/sets/>

[cid:image008.jpg@01CB49FA.E8BA3480]<http://www.xing.com/profile/LaSalle_BES>


[cid:image009.gif@01CB49FA.E8BA3480]<http://campuslasalle.tel/>



De: Toni-Jan Keith Monserrat [mailto:notifications@github.com]
Enviado el: sábado, 07 de mayo de 2016 18:17
Para: tjmonsi/chi2016-program <chi2016-program@noreply.github.com>
CC: Emiliano Labrador Ruiz de la Hermosa <eruiz@salleurl.edu>; Author <author@noreply.github.com>
Asunto: Re: [tjmonsi/chi2016-program] pdf version (#4)


Yes :) You can download them at https://chi2016.acm.org/wp/wp-content/uploads/2016/05/chi2016-program-final-for-web-2.pdf
